### ISSUE TITLE
Failure to compile on Go versions >= 1.17

### ISSUE THREAD

**Issue by terrabitz** [grantseltzer/libbpfgo-example#4]
When attempting to compile this code on Go versions >= 1.17, the following error is given:

```
CC=gcc CGO_CFLAGS="-I /usr/include/bpf" CGO_LDFLAGS="/usr/lib64/libbpf.a" go build -o libbpfgo-prog
# github.com/grantseltzer/libbpfgoexample
simple.bpf.c:9:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘#pragma’
    9 | } events SEC(".maps");
      | ^~~
simple.bpf.c:9:1: error: expected identifier or ‘(’ before ‘#pragma’
simple.bpf.c:13:1: error: expected identifier or ‘(’ before ‘#pragma’
   13 | SEC("kprobe/sys_execve")
      | ^~~
make: *** [Makefile:10: go_target] Error 2
```

It appears that the Go command is attempting to compile the `simple.bpf.c` file, despite the `//+build ignore` directive at the top. This is likely due to a recent change Go made to conditional build tags in Go 1.17: https://stackoverflow.com/a/67937234

**Comment by kgpp34** [comment]
I have attempted your scheme, but this bug also occur

clang -g -O2 -c -target bpf -o simple.bpf.o simple.bpf.c
CC=gcc CGO_CFLAGS="-I /usr/include/bpf" CGO_LDFLAGS="/home/ylh/linux-5.15.0/tools/bpf/bpftool/bootstrap/libbpf/libbpf.a" go build -o libbpfgo-prog

simple.bpf.c:10:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘#pragma’
   10 | } events SEC(".maps");
      | ^~~
simple.bpf.c:10:1: error: expected identifier or ‘(’ before ‘#pragma’
simple.bpf.c:14:1: error: expected identifier or ‘(’ before ‘#pragma’
   14 | SEC("kprobe/sys_execve")
      | ^~~

**Comment by cheneytianx** [comment]
When Go version >= 1.17, try `//go:build ignore`. Please refer to https://pkg.go.dev/cmd/go#hdr-Build_constraints

**Comment by zhwllq** [comment]
I have the same problem，Is there a solution？


CC=gcc CGO_CFLAGS="-I /usr/include/bpf/" CGO_LDFLAGS="/usr/src/linux-source-5.15.0/linux-source-5.15.0/tools/lib/bpf/libbpf.a" go build -o libbpfgo-prog
# libbpfgo-hello
In file included from simple.bpf.c:2:
simple.bpf.c:8:10: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘#pragma’
    8 | } events SEC(".maps");
      |          ^~~
simple.bpf.c:8:10: error: expected identifier or ‘(’ before ‘#pragma’
    8 | } events SEC(".maps");
      |          ^~~
simple.bpf.c:12:1: error: expected identifier or ‘(’ before ‘#pragma’
   12 | SEC("kprobe/sys_execve")
      | ^~~

**Comment by billhache** [comment]
Having the same issue. Any workaround?.
Thanks

**Comment by zer0-1s** [comment]
the same error ,golang 1.18.1

**Comment by zer0-1s** [comment]
```
package main

import "C"

import (
	"bytes"
	"encoding/binary"
	"fmt"
	"os"
	bpf "github.com/aquasecurity/libbpfgo"
)
```
and update go to 1.21  


![image](https://github.com/grantseltzer/libbpfgo-example/assets/62493040/804c67fc-99ad-42e5-9fcc-5ebb6d75bba8)
